### ISSUE TITLE
Hash part of an URL

### ISSUE THREAD

**Issue by geloescht** [troch/path-parser#10]
Is there a way of adding the hash as a parameter (or even query parameters in the hash) and if not, should it be added as a feature?

If I include a "#" character in a route, I get the following error:
```
Error: Could not parse path.
    at tokenise (removed non-helpful location in compiled code)
```

After a short look at the code I found out that quick fix would probably be to add "#" to the list of delimiters.

**Comment by troch** [comment]
This doesn't parse `#`, and is only meant to be used on the path part of the URL (and query params).
