### ISSUE TITLE
Able to parse plain querystring

### ISSUE THREAD

**Issue by bitinn** [troch/path-parser#2]
A route like `/clubs/:slug/posts?skip=0&limit=20` will cause parser to throw error. My expectation would be to leave querystring as it is. 

This maybe tricky to do, would checking each query contains `=` be enough?

A harder case would be `/clubs/:slug/posts?skip&limit=20`, in this case user may expect `build({ slug: 'abc', skip: 0 })` to work.

**Comment by troch** [comment]
Why would you want to pass `/clubs/:slug/posts?skip=0&limit=20` to the parser? For default values?

**Comment by bitinn** [comment]
Yeah, before using `path-parser`, I was using a custom regex to replace `:slug` with data. I can find a way to only use `/clubs/:slug/posts?:skip&:limit`, not a big deal.

**Comment by troch** [comment]
Yeah `/clubs/:slug/posts?:skip&:limit` would normally work, as `/clubs/:slug/posts?skip&limit` (`:` optional for query params). It shouldn't be too hard to support default values for query params.

**Comment by bitinn** [comment]
I have refactored my routes to avoid this problem (actually make managing default value easier, as I just need a single object for `build()` instead of writing `skip=0&limit=20`, so no complaint).

Being able to parse `?skip&limit=20` would be nice, but not really necessary for my use-case now, going to close this for now.
