### ISSUE TITLE
Error on last release

### ISSUE THREAD

**Issue by borjadotai** [troch/path-parser#20]
Hey there! 

Awesome work with this troch, just wanted to let you know that on the last release you've published, it breaks saying that Path is not a constructor. 

Just by using `const p = new Path('/api/names/:name/:number');`

But somehow it says that is not a constructor.
As soon as I downgrade to another version of the package, the same code works just fine!

**Comment by troch** [comment]
Two questions:

- By new version, do you mean 4.0.x? (i.e not the latest patch)
- How do you import `Path`? ES imports or commonJS require?

**Comment by borjadotai** [comment]
1. I'm not entirely sure, I just installed the one that came from running `npm i --save path-parser` which apparently is `path-parser@4.0.4`

2. `const Path = require('path-parser');`

**Comment by troch** [comment]
Ah, that's weird: https://github.com/troch/path-parser/commit/59f43c59a6467ec8a07ac44b18f8892d11f812c6 🤔 

I added a named export, and it caused rollup to compile the default export from `module.exports = Path` to `module.exports.default = Path`. Not sure if it is an issue with Rollup or TypeScript

**Comment by troch** [comment]
So the issue was with previous versions and a configuration option missed in `tsConfig.json`.

Correct way to import with `require` is:

```js
const { Path } = require('path-parser')
// or
const Path = require('path-parser').default
```

**Comment by borjadotai** [comment]
Great! Thanks for clarifying and updating the README 😉
Again, amazing work!
