### ISSUE TITLE
After V4.0.2 Path is broken

### ISSUE THREAD

**Issue by shivrajbadu** [troch/path-parser#21]
```sh
Version: path-parser@4.0.2, 4.0.3, 4.0.4
```

> NOTE: it is working as expected in `path-parser#4.0.1`

```js
const Path = require('path-parser');

const path = new Path('/test/:id/url');
```

And I am getting `TypeError: Path is not a constructor`.

we might need to double check https://github.com/troch/path-parser/commit/59f43c59a6467ec8a07ac44b18f8892d11f812c6 commit.

Thank you.

**Comment by troch** [comment]
@userrails related to #20: I've updated the docs, versions before 4.0.2 were exporting it incorrectly. It should be

```js
const { Path } = require('path-parser')
// or
const Path = require('path-parser').default
```

**Comment by shivrajbadu** [comment]
@troch Thanks
