### ISSUE TITLE
Plus not allowed in path param

### ISSUE THREAD

**Issue by aldeed** [troch/path-parser#22]
With path test: ":collection/:filename"

And actual path containing a `+`: `\foo\something+1.png`

`partialTest` returns null

It works if I change the default in `defaultOrConstrained` to this: `"[a-zA-Z0-9-_.~%':|\+]+"` (add `\+`)

Is this a bug or omitted for a reason? `+` is a valid literal non-escaped character in a path segment.

**Comment by troch** [comment]
Supported with latest version of path-parser
