### ISSUE TITLE
Support for `==` in parameters

### ISSUE THREAD

**Issue by MrLoh** [troch/path-parser#23]
Nice little library, very usefull and easy to use. 

I get base64 encoded ids from my backend. They look like this: `TW92aWU6MTI1OA==` (`btoa("Movie:1258")`), the parser can't handle these `==` in the strings. Could this be easily fixed somehow?

**Comment by troch** [comment]
Hey @MrLoh, you mean `==` in path parameters or query paramters?

**Comment by MrLoh** [comment]
path parameters. E.g. I'm matching path `/movie/:id` and want to extract the id from the URI `/movie/TW92aWU6MTI1OA==`.

**Comment by troch** [comment]
Supported with latest version of path-parser
