### ISSUE TITLE
Better type definition for `TestMatch`

### ISSUE THREAD

**Issue by StefanoMagrassi** [troch/path-parser#28]
[Here](https://github.com/troch/path-parser/blob/master/modules/Path.ts#L65) `TestMatch` type is defined as really generic `object | null`, but if we look at the code in the [`urlTest`](https://github.com/troch/path-parser/blob/master/modules/Path.ts#L286) method (which computes and returns the `TestMatch`) the right definition should be `{[k: string]: string} | null` (a map instead of an object).

I guess that this would be a breaking change, even if only for Typescript users, and it will lead to bumping the major version of the package.

PR very soon ;)

**Comment by troch** [comment]
Type def fixed in #42
