### ISSUE TITLE
TypeError: PathParser is not a constructor

### ISSUE THREAD

**Issue by ibc** [troch/path-parser#30]
* path-parser@4.2.0

I just upgraded from version 3.x.x to 4.2.0, and got the above error. And makes sense since, in 4.x.x, `require('path-parser')` returns an Object:

```js
const PathParser = require('path-parser');

> PathParser
{ Path: { [Function: Path] createPath: [Function] },
  default: { [Function: Path] createPath: [Function] } }
```

So, if used in Node, `const PathParser = require('path-parser').default` is required. But the CHANGELOG says nothing about it.

**Comment by troch** [comment]
`default` export will be removed in next major (#42)
