### ISSUE TITLE
Unexpected behavior of partialTest

### ISSUE THREAD

**Issue by petermikitsh** [troch/path-parser#9]
I was under the impression `partialTest` operated a little differently. For example:

```js
const p = new Path('/:foo/:bar');
p.partialTest('/baz') // #=> null
```

actual result: `null`
expected result: `{foo: 'baz'}`

Is it possible to use the API for partial URL matches? My url will sometimes have a `:bar` and sometimes it won't.

**Comment by troch** [comment]
It works the other way round: you pass to `partialTest` a string which may include your path, not a string included in your path.

For what you want to do, look at [route-node](/troch/route-node)

**Comment by petermikitsh** [comment]
I found [route-parser](https://github.com/rcs/route-parser); it works quite well for this use case. Closing this.
